kineticpop/kineticapp/urls.py
from django.urls import path
from kineticapp import views

# TEMPLATE TAGGING

app_name = 'kineticapp'

urlpatterns = [
    path("illustrations", views.illustrations, name="illustrations"),
    path("characters", views.characters, name="characters"),
    path("graphics", views.graphics, name="graphics"),
    path("contact", views.contact, name="contact"),
    path("success", views.success, name="success"),
    path('', views.index, name='index'),
]

kineticpop/kineticpop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from kineticapp import views

# import settings in order to create the static/media URLs
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('kineticapp/', include('kineticapp.urls')),
    path('admin/', admin.site.urls),
    path('alex_favicon.svg', RedirectView.as_view(url=staticfiles_storage.url('alex_favicon.svg')),),
]

# this is done in conjunction with file.images.url in the html in order for it to display images on each page
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kineticpop/kineticapp/models.py
from django.db import models

# Create your models here.

# For contact form, includes individual's name, email, and comments.
class Contact(models.Model):
    full_name = models.CharField(max_length=70)
    email = models.EmailField(max_length=70, unique=True)
    comments = models.TextField(max_length=100)

class Characters(models.Model):
    image = models.ImageField(null=False, blank=False, 
        upload_to="characters/")

    name = models.CharField(max_length=70, default='Character - ') 

    def __str__(self):
        return self.name

class Graphics(models.Model):
    image = models.ImageField(null=False, blank=False, 
        upload_to="graphics/")

    name = models.CharField(max_length=70, default='Graphic - ')

    def __str__(self):
        return self.name

class Illustrations(models.Model):
    image = models.ImageField(null=False, blank=False, 
        upload_to="illustrations/")

    name = models.CharField(max_length=70, default='Illustration - ')

    def __str__(self):
        return self.name

kineticpop/kineticapp/forms.py
from django import forms
from .models import Contact


#ModelForm allows the HTML form to save data to a database
#class Meta connects the form to our Contact model via model attribute
class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

kineticpop/kineticapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import ContactForm
from .models import Characters, Graphics, Illustrations

# Create your views here.

def index(request):
    return render(request, "kineticapp/index.html")

# if statement in contact causes a reaction. if someone submits a valid form, the form info will be stored.
# if there is a post request (which it is set up to be so), and submitted/valid -- form will save and return success page.
# form.save() runs Django's built in form verifying function.
def contact(request):
    form = ContactForm()

    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return render(request, "kineticapp/success.html")
        else:
            return HttpResponse("invalid")

    context = {"form": form}
    return render(request, "kineticapp/contact.html", context)

def success(request):
    return render(request, "kineticapp/success.html")

# create a objects.all() to obtain all the objects uploaded to each model/admin section (i.e. - Characters, Illustrations, Graphics)
# context allows you to plugin to the return render
def graphics(request):
    graphics = Graphics.objects.all()
    context = {'graphics': graphics}
    return render(request, "kineticapp/graphics.html", context)

def illustrations(request):
    illustrations = Illustrations.objects.all()
    context = {'illustrations': illustrations}
    return render(request, "kineticapp/illustrations.html", context)

def characters(request):
    characters = Characters.objects.all()
    context = {'characters': characters}
    return render(request, "kineticapp/characters.html", context)

kineticpop/templates/kineticapp/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <![endif]-->
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Alex's Portfolio</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- for bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <!-- <link href="static/css/cover.css" rel="stylesheet"> -->
        <link rel="shortcut icon" href="{% static 'alex_favicon.svg' %}"/>
        <!-- for social media icons! -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'css/social_media.css' %}">
    </head>
    <body class="d-flex h-100 text-center text-white bg-dark">


        <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
          <header class="mb-auto bg-dark">
            <div class="container">
              <a href="{% url 'index' %}">
              <img src="{% static 'alex_logo.svg' %}" class="float-md-start mb-0 rounded-circle" width="60" height="60">
              </a>
              <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link" href="{% url 'kineticapp:graphics' %}">Graphics</a>
                <a class="nav-link" href="{% url 'kineticapp:illustrations' %}">Illustrations</a>
                <a class="nav-link" href="{% url 'kineticapp:characters' %}">Characters</a>
                <a class="nav-link" href="{% url 'kineticapp:contact' %}">Contact</a>
                <a class="nav-link" href="{% url 'index' %}">Home</a>
              </nav>
            </div>
          </header>


        <div class="container">
            {% block body_block %}
            <!-- Anything here will not be transferred to other htmls -->
            {% endblock %}
        </div>


        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

          <br><br><br>

        <footer class="mt-auto text-white-50">
            <p><a href="https://www.instagram.com/kineticpop/" class="text-white" target="_blank" rel="noopener noreferrer">Alex's World</a>, Brought to you by <a href="https://www.instagram.com/jvictor.silva.15/" class="text-white" target="_blank" rel="noopener noreferrer">Victor Silva</a>.</p>
            
            <div class="container text-center">
              <a href="https://www.facebook.com/kineticpop/" class="fa fa-facebook" target="_blank" rel="noopener noreferrer"></a>
              <a href="https://twitter.com/kineticpopart" class="fa fa-twitter" target="_blank" rel="noopener noreferrer"></a>
              <a href="https://www.instagram.com/kineticpop/" class="fa fa-instagram" target="_blank" rel="noopener noreferrer"></a>
              <a href="https://www.twitch.tv/kineticpop" class="fa fa-twitch" target="_blank" rel="noopener noreferrer"></a>
              <a href="https://www.linkedin.com/in/alex-porcayo-1309a9178" class="fa fa-linkedin" target="_blank" rel="noopener noreferrer"></a>
            </div>  
        </footer>
        </div>

        <!-- for bootstrap -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>
</html>

kineticpop/templates/kineticapp/base_album.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Alex's Portfolio</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">

    <!-- for social media icons! -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/social_media.css' %}">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>




<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Home to one of South Florida's art and design creator. Currently the asset coordinator at Basic Fun! In addition to having the artistic trait passed down from his father, 
            Alex has spent years honing his artistic abilities. If you are here and would like to hire Alex for some freelance work, please visit the contact page. 
            Or, if you are just visiting feel free to look around. If you would like to support Alex, please visit our support page.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <a class="text-white" href="{% url 'kineticapp:contact' %}">
          <h4>Contact</h4>
          </a>
          
          <!-- <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul> -->
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="{% url 'index' %}" class="navbar-brand d-flex align-items-center">
        <!-- <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg> -->
        <img src="{% static 'alex_logo.svg' %}" class="float-md-start mb-0 rounded-circle" width="60" height="60">
        <strong>Album</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>



</header>


{% block body_block %}
<!-- Anything here will not be transferred to other htmls -->
{% endblock %}


<footer class="text-muted py-5 bg-dark">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p><a href="https://www.instagram.com/kineticpop/" target="_blank" rel="noopener noreferrer">Alex's World</a>, Brought to you by <a href="https://www.instagram.com/jvictor.silva.15/" target="_blank" rel="noopener noreferrer">Victor Silva</a>.</p>
    <p class="mb-0">Like what you see? 
      Get in touch with Alex by visiting the <a href="{% url 'kineticapp:contact' %}">contact</a> page.</p>
    <br>
    <div class="container text-center">
      <a href="https://www.facebook.com/kineticpop/" class="fa fa-facebook" target="_blank" rel="noopener noreferrer"></a>
      <a href="https://twitter.com/kineticpopart" class="fa fa-twitter" target="_blank" rel="noopener noreferrer"></a>
      <a href="https://www.instagram.com/kineticpop/" class="fa fa-instagram" target="_blank" rel="noopener noreferrer"></a>
      <a href="https://www.twitch.tv/kineticpop" class="fa fa-twitch" target="_blank" rel="noopener noreferrer"></a>
      <a href="https://www.linkedin.com/in/alex-porcayo-1309a9178" class="fa fa-linkedin" target="_blank" rel="noopener noreferrer"></a>
      </div>
  </div>
</footer>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

      
  </body>
</html>

kineticpop/templates/kineticapp/characters.html
<!DOCTYPE html>

{% extends "kineticapp/base_album.html" %}
    {% block body_block %}


<main>

  <!-- INTRO TO ALBUM/INFO ABOUT PAGE -->
  
      <section class="py-5 text-center container">
        <div class="row py-lg-5">
          <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Character Design Album</h1>
            <hr>
            <p class="lead text-muted">From company work to freelance gigs to drawing for fun, this album includes all drawings done related to character design. 
              There is a lot that goes on when creating a charcter, here is where imagination and references are key. 
            </p>
            <p>
              <a href="{% url 'kineticapp:illustrations' %}" class="btn btn-secondary my-2">To the illustrations page</a>
              <a href="{% url 'kineticapp:graphics' %}" class="btn btn-secondary my-2">To the graphics design page</a>
            </p>
            <hr>
          </div>
        </div>
      </section>
    
<!-- the for loop allows for the thumbnails to loop through uploaded images from the admin page. 
  this will connect to the images in each respective folder. 
      The src is image.url in order to display the image in the webpage. This is connected to the urls.py in the project. -->
  
<div class="container bg-light">

  <div class="row">
    {% for character in characters %}

      <div class="col-lg-4 col-sm-6 img-thumbnail">
        <img class="img-fluid" src="{{character.image.url}}" alt="Characters">
      </div>
      
    {% empty %}
      <h3>Nothing to see here...</h3>
    {% endfor %}
  </div>
</div>


<br><br><br><br>
  
</main>


{% endblock %}

kineticpop/templates/kineticapp/contact.html
<!DOCTYPE html>

{% extends "kineticapp/base_album.html" %}
    {% block body_block %}
    {% load static %}
    <br><br>
    

  <div class="container p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold text-center">Contact Alex</h1>
      <p class="fs-4" style="text-align: center;">Alex is currently on several social media platforms, and may be contacted via these platforms.
        You may also submit your information below, and Alex will contact you as soon as possible. 
        Feel free to inquire about possible work request or if you would just like to leave Alex some encouragement!</p>
        <div class="container text-center">
        <a href="https://www.facebook.com/kineticpop/" class="fa fa-facebook" target="_blank" rel="noopener noreferrer"></a>
        <a href="https://twitter.com/kineticpopart" class="fa fa-twitter" target="_blank" rel="noopener noreferrer"></a>
        <a href="https://www.instagram.com/kineticpop/" class="fa fa-instagram" target="_blank" rel="noopener noreferrer"></a>
        <a href="https://www.twitch.tv/kineticpop" class="fa fa-twitch" target="_blank" rel="noopener noreferrer"></a>
        <a href="https://www.linkedin.com/in/alex-porcayo-1309a9178" class="fa fa-linkedin" target="_blank" rel="noopener noreferrer"></a>
        </div>
    </div>
  </div>

  <br><br>

  <div class="container max width bg-light">
      <!-- form action="" with a blank action tells the browser to submit the form back to the same URL -->
      <form class="row row-cols-lg-auto g-3 align-items-center" method="POST">
        <!-- csrf is the required security measures of django for a form -->
        {% csrf_token %}
        
          <div class="col-12">
            <label class="visually-hidden" for="full name">Name</label>
            <div class="input-group">
              <div class="input-group-text">Full Name</div>
              <input type="text" class="form-control" id="full_name" name="full_name" placeholder="First and Last (Required)" required minlength="4" maxlength="70">
            </div>
          </div>

          <div class="col-12">
            <label class="visually-hidden" for="email">Email</label>
            <div class="input-group">
              <div class="input-group-text">Email</div>
              <input type="email" class="form-control" id="email" name="email" placeholder="email@email.com (Required)" required minlength="4" maxlength="70">
            </div>
          </div>

          <div class="col-12">
            <label class="visually-hidden" for="comments">Comments</label>
            <div class="input-group">
              <div class="input-group-text">Comments</div>
              <input type="text" class="form-control" id="comments" name="comments" placeholder="Comments" maxlength="100">
            </div>
          </div>

          <div class="col-12">
            <button type="submit" value="Submit" class="btn btn-primary">Send Message</button>
          </div>
        </form>

  </div>

  <br><br>

  <div class="container p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
      <h2 class="display-5 fw-bold text-center">Donate</h2>
      <p class="fs-4" style="text-align: center;">If you would like to support this up and coming artist, consider supporting via his <a href="https://ko-fi.com/kineticpopart" target="_blank" rel="noopener noreferrer">Ko-fi</a> link.
        All donations are highly appreciated!</p>
    </div>
  </div>



{% endblock %}

kineticpop/templates/kineticapp/graphics.html
<!DOCTYPE html>

{% extends "kineticapp/base_album.html" %}
    {% block body_block %}

    {% load static %}
<main>

<!-- INTRO TO ALBUM/INFO ABOUT PAGE -->

    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">Graphic Design Album</h1>
          <hr>
          <p class="lead text-muted">Being a part of a toy factory's graphic design team is no joke. 
            These years have been tough, my beard has grown long and and thick, and the bags under my eyes have darkened. 
            Fortunately, my graphic design skills have grown tremendously. 
            Check out below some of my graphic design work.</p>
          <p>
            <a href="{% url 'kineticapp:illustrations' %}" class="btn btn-secondary my-2">To the illustrations page</a>
            <a href="{% url 'kineticapp:characters' %}" class="btn btn-secondary my-2">To the character design page</a>
          </p>
          <hr>
        </div>
      </div>
    </section>
    
  
<!-- the for loop allows for the thumbnails to loop through uploaded images from the admin page. 
  this will connect to the images in each respective folder. 
      The src is image.url in order to display the image in the webpage. This is connected to the urls.py in the project. -->

<div class="container bg-light">


  <div class="row">
    {% for graphic in graphics %}

      <div class="col-lg-4 col-sm-6 img-thumbnail">
        <img class="img-fluid" src="{{graphic.image.url}}" alt="Graphics">
      </div>
      
    {% empty %}
      <h3>Nothing to see here...</h3>
    {% endfor %}
  </div>
</div>

<br><br><br><br>

</main>


{% endblock %}

kineticpop/templates/kineticapp/illustrations.html
<!DOCTYPE html>

{% extends "kineticapp/base_album.html" %}
    {% block body_block %}


<main>

  <!-- INTRO TO ALBUM/INFO ABOUT PAGE -->
  
      <section class="py-5 text-center container">
        <div class="row py-lg-5">
          <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Illustrations Album</h1>
            <hr>
            <p class="lead text-muted">The illustrations Album is art mostly done for fun though some have been a part of work projects. 
              One of the biggest projects have the goblins made for a boardgame.</p>
            <p>
              <a href="{% url 'kineticapp:graphics' %}" class="btn btn-secondary my-2">To the graphics design page</a>
              <a href="{% url 'kineticapp:characters' %}" class="btn btn-secondary my-2">To the character design page</a>
            </p>
            <hr>
          </div>
        </div>
      </section>
    
<!-- the for loop allows for the thumbnails to loop through uploaded images from the admin page. 
  this will connect to the images in each respective folder. 
      The src is image.url in order to display the image in the webpage. This is connected to the urls.py in the project. -->
  
  
<div class="container bg-light">


  <div class="row">

    {% for illustration in illustrations %}

      <div class="col-lg-4 col-sm-6 img-thumbnail">
        <img class="img-fluid" src="{{illustration.image.url}}" alt="Illustrations">
      </div>
      
    {% empty %}
      <h3>Nothing to see here...</h3>
    {% endfor %}

  </div>
</div>

<br><br><br><br>
  
</main>


{% endblock %}

kineticpop/templates/kineticapp/index.html
<!DOCTYPE html>

{% extends "kineticapp/base.html" %}
    {% block body_block %}
        
        <br><br><br>    
        <h1>Welcome to all things Alex.</h1>
        <br>
        <p>Home to one of South Florida's art and design creator. Currently the asset coordinator at Basic Fun! In addition to having the artistic trait passed down from his father, 
          Alex has spent years honing his artistic abilities. If you are here and would like to hire Alex for some freelance work, please visit the contact page. 
          Or, if you are just visiting feel free to look around. If you would like to support Alex, please visit our support page.</p>
        <br><br>  

      <div class="album py-5 bg-dark rounded">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

              
              <div class="col">
                <div class="card bg-dark rounded-circle">
                  <!-- <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></svg> -->
                  <a href="{% url 'kineticapp:graphics' %}">
                  <img src="https://cdna.artstation.com/p/assets/images/images/037/829/548/large/alex-porcayo-60b10105-a449-42e9-8dca-27189947de02-rw-1920.jpg?1621430561" class="bd-placeholder-img card-img-top rounded-circle" max-width="200" max-height="415">
                  </a>
                </div>
                <div class="card-body">
                  <h4 class="text-center"><a href="{% url 'kineticapp:graphics' %}" class="text-white">Graphics Design</a></h4>
                  <div>
                    <p class="d-flex justify-content-between align-items-center">
                        Brand equity audit Strategic direction Competitive review Audience analysis
                    </p>
                  </div>
                </div>
              </div>
              
              <div class="col">
                <div class="card bg-dark rounded-circle">
                  <!-- <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></svg> -->
                  <a href="{% url 'kineticapp:illustrations' %}">
                  <img src="https://cdnb.artstation.com/p/assets/images/images/037/814/857/large/alex-porcayo-battle-dental-final.jpg?1621387563" class="bd-placeholder-img card-img-top rounded-circle" max-width="200" max-height="415">
                  </a>
                </div>
                <div class="card-body">
                  <h4 class="text-center"><a href="{% url 'kineticapp:illustrations' %}" class="text-white">Illustration Pieces</a></h4>
                  <div>
                    <p class="d-flex justify-content-between align-items-center">
                        Brand equity audit Strategic direction Competitive review Audience analysis
                    </p>
                  </div>
                </div>
              </div>
              
              <div class="col">
                <div class="card bg-dark rounded-circle">
                  <!-- <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></svg> -->
                  <a href="{% url 'kineticapp:characters' %}">
                  <img src="https://cdnb.artstation.com/p/assets/images/images/037/817/753/large/alex-porcayo-187065830-187425999810855-218021805997180565-n.jpg?1621397340" class="bd-placeholder-img card-img-top rounded-circle" max-width="200" max-height="415">
                  </a>
                </div>
                <div class="card-body">
                  <h4 class="text-center"><a href="{% url 'kineticapp:characters' %}" class="text-white">Character Design</a></h4>
                  <div>
                    <p class="d-flex justify-content-between align-items-center">
                        Brand equity audit Strategic direction Competitive review Audience analysis
                    </p>
                  </div>
                </div>
              </div>

            </div>
        </div>
      </div>


      

    {% endblock %}

kineticpop/templates/kineticapp/success.html
<!DOCTYPE html>

{% extends "kineticapp/base_album.html" %}
    {% block body_block %}

    <br><br>
    

  <div class="container p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold text-center">Success!!!</h1>

      <p class="fs-4" style="text-align: center;">Alex has received your contact information and will contact you as soon as possible! 
        In the mean time, feel free to check out some of his work on social media!</p>

        <div class="container text-center">
        <a href="https://www.facebook.com/kineticpop/" class="fa fa-facebook"></a>
        <a href="https://twitter.com/kineticpopart" class="fa fa-twitter"></a>
        <a href="https://www.instagram.com/kineticpop/" class="fa fa-instagram"></a>
        <a href="https://www.twitch.tv/kineticpop" class="fa fa-twitch"></a>
        <a href="https://www.linkedin.com/in/alex-porcayo-1309a9178" class="fa fa-linkedin"></a>
        </div>
    </div>
  </div>

  <br><br>


{% endblock %}